<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"景点管理",
                        "menuJump":"列表",
                        "tableName":"jingdian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"景点收藏管理",
                        "menuJump":"列表",
                        "tableName":"jingdianCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"景点订单管理",
                        "menuJump":"列表",
                        "tableName":"jingdianOrder"
                    }
                ],
                "menu":"景点管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"酒店管理",
                        "menuJump":"列表",
                        "tableName":"jiudian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"酒店收藏管理",
                        "menuJump":"列表",
                        "tableName":"jiudianCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"酒店订单管理",
                        "menuJump":"列表",
                        "tableName":"jiudianOrder"
                    }
                ],
                "menu":"酒店管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"美食管理",
                        "menuJump":"列表",
                        "tableName":"meishi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"美食收藏管理",
                        "menuJump":"列表",
                        "tableName":"meishiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"美食订单管理",
                        "menuJump":"列表",
                        "tableName":"meishiOrder"
                    }
                ],
                "menu":"美食管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"娱乐项目管理",
                        "menuJump":"列表",
                        "tableName":"yulexiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"娱乐项目收藏管理",
                        "menuJump":"列表",
                        "tableName":"yulexiangmuCollection"
                    }
					,
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"娱乐项目订单",
					    "menuJump":"列表",
					    "tableName":"yulexiangmuOrder"
					}
                ],
                "menu":"娱乐项目管理"
            }
			 ,{
				"child":[
					{
						"buttons":[
							"查看",
							"新增",
							"修改",
							"删除"
						],
						"menu":"相册管理",
						"menuJump":"列表",
						"tableName":"xiangche"
					}
				],
				"menu":"相册管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"景点类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJingdian"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"景点等级管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJingdianDengji"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"酒店星级管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJiudian"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"相册类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryXiangche"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"新闻管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"景点管理",
	                    "menuJump":"列表",
	                    "tableName":"jingdian"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"景点收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"jingdianCollection"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"景点订单管理",
	                    "menuJump":"列表",
	                    "tableName":"jingdianOrder"
	                }
	            ],
	            "menu":"景点管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"酒店管理",
	                    "menuJump":"列表",
	                    "tableName":"jiudian"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"酒店收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"jiudianCollection"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"酒店订单管理",
	                    "menuJump":"列表",
	                    "tableName":"jiudianOrder"
	                }
	            ],
	            "menu":"酒店管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"美食管理",
	                    "menuJump":"列表",
	                    "tableName":"meishi"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"美食收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"meishiCollection"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"美食订单管理",
	                    "menuJump":"列表",
	                    "tableName":"meishiOrder"
	                }
	            ],
	            "menu":"美食管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"娱乐项目管理",
	                    "menuJump":"列表",
	                    "tableName":"yulexiangmu"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"娱乐项目收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"yulexiangmuCollection"
	                }
					,
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"娱乐项目订单",
					    "menuJump":"列表",
					    "tableName":"yulexiangmuOrder"
					}
	            ],
	            "menu":"娱乐项目管理"
	        }
			,{
				"child":[
					{
						"buttons":[
							"查看",
							"新增",
							"修改",
							"删除"
						],
						"menu":"相册管理",
						"menuJump":"列表",
						"tableName":"xiangche"
					}
				],
				"menu":"相册管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"新闻管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"新闻管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
